import { NextRequest } from 'next/server'
import {
  allData,
  casualStyleData,
  favouritePicksData,
  summerSareesData,
  grandHeritageSaleData,
  engagementData,
  mehendiData,
  sangeetData,
  haldiData,
  banarasiData,
  paithaniData,
  kanjivaramData,
  patolaData,
  organzaData,
  southSilkData,
  maheshwariSilkData,
  luxeCollectionData,
  dolaSilkData,
  brassoData,
  printedData,
  kalamkariData,
  ajrakhData,
  redSareeData,
  blueSareeData,
  greenSareeData,
  yellowSareeData,
  orangeSareeData,
  purpleSareeData,
  pinkSareeData,
  brownSareeData,
  graySareeData,
  blackSareeData,
  whiteSareeData,
  cyanSareeData,
  magentaSareeData,
  tealSareeData,
  limeSareeData,
  indigoSareeData,
  violetSareeData,
  amberSareeData,
  multiColorSareeData,
  silkSareeData,
  cottonSareeData,
  chiffonSareeData,
  georgetteSareeData,
  linenSareeData,
  satinSareeData,
  celebritySareeData,
} from './collection1'

type CollectionType = {
  [key: string]: (req: NextRequest) => Promise<{
    products: any[]
    totalProducts: number
  }> // Index signature
}

const collectionData: CollectionType = {
  all: allData,
  'favourite-picks': favouritePicksData,
  'summer-sarees': summerSareesData,
  'casual-style': casualStyleData,
  'grand-heritage-sale': grandHeritageSaleData,
  'engagement-sarees': engagementData,
  'mehendi-sarees': mehendiData,
  'sangeet-sarees': sangeetData,
  'haldi-sarees': haldiData,
  'banarasi-saree': banarasiData,
  'paithani-saree': paithaniData,
  'kanjivaram-saree': kanjivaramData,
  'patola-sarees': patolaData,
  'organza-saree': organzaData,
  'south-silk-saree': southSilkData,
  'maheshwari-silk-saree': maheshwariSilkData,
  'luxe-collection': luxeCollectionData,
  'silk-sarees': silkSareeData,
  'cotton-saree': cottonSareeData,
  'linen-sarees': linenSareeData,
  'chiffon-saree': chiffonSareeData,
  'satin-silk-saree': satinSareeData,
  'georgette-saree': georgetteSareeData,
  'dola-silk-saree': dolaSilkData,
  'brasso-saree': brassoData,
  'printed-sarees': printedData,
  'kalamkari-sarees': kalamkariData,
  'ajrakh-sarees': ajrakhData,
  'red-sarees': redSareeData,
  'blue-sarees': blueSareeData,
  'green-sarees': greenSareeData,
  'yellow-sarees': yellowSareeData,
  'orange-sarees': orangeSareeData,
  'purple-sarees': purpleSareeData,
  'pink-sarees': pinkSareeData,
  'brown-sarees': brownSareeData,
  'gray-sarees': graySareeData,
  'black-sarees': blackSareeData,
  'white-sarees': whiteSareeData,
  'cyan-sarees': cyanSareeData,
  'magenta-sarees': magentaSareeData,
  'teal-sarees': tealSareeData,
  'lime-sarees': limeSareeData,
  'indigo-sarees': indigoSareeData,
  'violet-sarees': violetSareeData,
  'amber-sarees': amberSareeData,
  'multi-color-sarees': multiColorSareeData,
  'celeb-sarees': celebritySareeData,
}

export default collectionData
