export enum ColorOptionsEnum {
  Red = 'red',
  Blue = 'blue',
  Green = 'green',
  Yellow = 'yellow',
  Orange = 'orange',
  Purple = 'purple',
  Pink = 'pink',
  Brown = 'brown',
  Gray = 'gray',
  Black = 'black',
  White = 'white',
  Cyan = 'cyan',
  Magenta = 'magenta',
  Teal = 'teal',
  Lime = 'lime',
  Indigo = 'indigo',
  Violet = 'violet',
  Amber = 'amber',
  MultiColor = 'multi-color',
}

export enum FabricOptionsEnum {
  Silk = 'silk',
  Cotton = 'cotton',
  Chiffon = 'chiffon',
  Georgette = 'georgette',
  Banarasi = 'banarasi',
  Kanjeevaram = 'kanjeevaram',
  Linen = 'linen',
  Satin = 'satin',
  Net = 'net',
  Velvet = 'velvet',
  Organza = 'organza',
  Jute = 'jute',
  Crepe = 'crepe',
  Taant = 'taant',
  Patola = 'patola',
  Bandhani = 'bandhani',
  Dhakai = 'dhakai',
  Tussar = 'tussar',
  Kota = 'kota',
  Sambalpuri = 'sambalpuri',
}
