export const sareeCollectionsArray = [
  {
    id: 'favouritePicks',
    name: 'sareeCollections[]',
    value: 'favourite-picks',
    label: 'Favourite Picks',
  },
  {
    id: 'summerSarees',
    name: 'sareeCollections[]',
    value: 'summer-sarees',
    label: 'Summer Sarees',
  },
  {
    id: 'casualStyle',
    name: 'sareeCollections[]',
    value: 'casual-style',
    label: 'Casual Style',
  },
  {
    id: 'grandHeritageSale',
    name: 'sareeCollections[]',
    value: 'grand-heritage-sale',
    label: 'Grand Heritage Sale',
  },
  {
    id: 'engagement',
    name: 'sareeCollections[]',
    value: 'engagement-sarees',
    label: 'Engagement',
  },
  {
    id: 'mehendi',
    name: 'sareeCollections[]',
    value: 'mehendi-sarees',
    label: 'Mehendi',
  },
  {
    id: 'sangeet',
    name: 'sareeCollections[]',
    value: 'sangeet-sarees',
    label: 'Sangeet',
  },
  {
    id: 'haldi',
    name: 'sareeCollections[]',
    value: 'haldi-sarees',
    label: 'Haldi',
  },
  {
    id: 'banarasi',
    name: 'sareeCollections[]',
    value: 'banarasi-saree',
    label: 'Banarasi Saree',
  },
  {
    id: 'paithani',
    name: 'sareeCollections[]',
    value: 'paithani-saree',
    label: 'Paithani Saree',
  },
  {
    id: 'kanjivaram',
    name: 'sareeCollections[]',
    value: 'kanjivaram-saree',
    label: 'Kanjivaram Saree',
  },
  {
    id: 'patola',
    name: 'sareeCollections[]',
    value: 'patola-sarees',
    label: 'Patola Sarees',
  },
  {
    id: 'organza',
    name: 'sareeCollections[]',
    value: 'organza-saree',
    label: 'Organza Saree',
  },
  {
    id: 'southSilk',
    name: 'sareeCollections[]',
    value: 'south-silk-saree',
    label: 'South Silk Saree',
  },
  {
    id: 'maheshwariSilk',
    name: 'sareeCollections[]',
    value: 'maheshwari-silk-saree',
    label: 'Maheshwari Silk Saree',
  },
  {
    id: 'luxeCollection',
    name: 'sareeCollections[]',
    value: 'luxe-collection',
    label: 'Luxe Collection',
  },
  {
    id: 'dolaSilk',
    name: 'sareeCollections[]',
    value: 'dola-silk-saree',
    label: 'Dola Silk Saree',
  },
  {
    id: 'brasso',
    name: 'sareeCollections[]',
    value: 'brasso-saree',
    label: 'Brasso Saree',
  },
  {
    id: 'printed',
    name: 'sareeCollections[]',
    value: 'printed-sarees',
    label: 'Printed Sarees',
  },
  {
    id: 'kalamkari',
    name: 'sareeCollections[]',
    value: 'kalamkari-sarees',
    label: 'Kalamkari Sarees',
  },
  {
    id: 'ajrakh',
    name: 'sareeCollections[]',
    value: 'ajrakh-sarees',
    label: 'Ajrakh Sarees',
  },
]

export const colorOptions = [
  { name: 'red', content: 'Red' },
  { name: 'blue', content: 'Blue' },
  { name: 'green', content: 'Green' },
  { name: 'yellow', content: 'Yellow' },
  { name: 'orange', content: 'Orange' },
  { name: 'purple', content: 'Purple' },
  { name: 'pink', content: 'Pink' },
  { name: 'brown', content: 'Brown' },
  { name: 'gray', content: 'Gray' },
  { name: 'black', content: 'Black' },
  { name: 'white', content: 'White' },
  { name: 'cyan', content: 'Cyan' },
  { name: 'magenta', content: 'Magenta' },
  { name: 'teal', content: 'Teal' },
  { name: 'lime', content: 'Lime' },
  { name: 'indigo', content: 'Indigo' },
  { name: 'violet', content: 'Violet' },
  { name: 'amber', content: 'Amber' },
  { name: 'multi-color', content: 'Multi Color' },
]

export const fabricOptions = [
  { value: 'silk', content: 'Silk' },
  { value: 'cotton', content: 'Cotton' },
  { value: 'chiffon', content: 'Chiffon' },
  { value: 'georgette', content: 'Georgette' },
  { value: 'banarasi', content: 'Banarasi' },
  { value: 'kanjeevaram', content: 'Kanjeevaram' },
  { value: 'linen', content: 'Linen' },
  { value: 'satin', content: 'Satin' },
  { value: 'net', content: 'Net' },
  { value: 'velvet', content: 'Velvet' },
  { value: 'organza', content: 'Organza' },
  { value: 'jute', content: 'Jute' },
  { value: 'crepe', content: 'Crepe' },
  { value: 'taant', content: 'Taant' },
  { value: 'patola', content: 'Patola' },
  { value: 'bandhani', content: 'Bandhani' },
  { value: 'dhakai', content: 'Dhakai' },
  { value: 'tussar', content: 'Tussar' },
  { value: 'kota', content: 'Kota' },
  { value: 'sambalpuri', content: 'Sambalpuri' },
]
